# OpenAI配置
openai_api_key: ""  # 请在此处填入您的OpenAI API密钥
model: "gpt-3.5-turbo"  # 使用的模型
temperature: 0.7  # 生成的随机性，值越高越随机
base_url: "https://api.openai.com/v1"  # API基础URL

# LangSmith配置
langsmith_api_key: ""  # 请在此处填入您的LangSmith API密钥
prompt_name: "story_prompt"  # 从LangSmith拉取的prompt名称

# 历史记录设置
history_length: 50  # 保留的历史记录长度
