# LLM配置
google_api_key: "AIzaSyDxqCA3kmFZPygRszaNYzQ8AYXy19vFDhA"  # 请替换为您的Google API密钥
openai_api_key: "sk-d95700a50e384ede873b10befc2f0633"  # 请替换为您的OpenAI兼容API密钥
model: "qwen-plus"
temperature: 0.7
max_tokens: 150
history_length: 50  # 历史记录长度
base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"  # 请替换为您的API基础URL
